lib/ab_test_api_web/router.ex
defmodule AbTestApiWeb.Router do
  use AbTestApiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AbTestApiWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/experiments", ExperimentController, only: [:new, :create, :show, :delete, :index]
  end

  # Other scopes may use custom stacks.
  scope "/api", AbTestApiWeb.Api, as: :api do
    pipe_through :api

    resources "/experiments", ExperimentController, only: [:index]
  end
end

lib/ab_test_api_web/views/layout_view.ex
defmodule AbTestApiWeb.LayoutView do
  use AbTestApiWeb, :view
end

lib/ab_test_api_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>AbTestApi · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "Experiments", to: Routes.experiment_path(@conn, :index) %></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>